"""
Tests for database migrations.

This module contains tests to verify that all migrations are created
and applied correctly for all apps in the project.
"""

from django.test import TestCase
from django.db import connection
from django.apps import apps


class MigrationTest(TestCase):
    """Test suite for verifying database migrations."""

    def test_all_models_have_tables_in_database(self):
        """
        Test that all Django models have corresponding tables in database.

        This verifies that migrations have been created and applied for all
        models defined in the project apps.
        """
        # Get all installed app models
        all_models = apps.get_models()

        # Get all table names in database
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
            """)
            db_tables = [row[0] for row in cursor.fetchall()]

        # Check each model has a corresponding table
        for model in all_models:
            # Skip Django's built-in models like ContentType, Session, etc.
            app_label = model._meta.app_label
            if app_label in ['accounts', 'transactions', 'reports']:
                table_name = model._meta.db_table
                self.assertIn(
                    table_name,
                    db_tables,
                    f"Table {table_name} for model {model.__name__} "
                    f"not found in database. Migration may not be applied."
                )

    def test_accounts_userprofile_model_exists(self):
        """Test that UserProfile model from accounts app has database table."""
        from accounts.models import UserProfile

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_name = %s
            """, [UserProfile._meta.db_table])
            result = cursor.fetchone()

        self.assertIsNotNone(
            result,
            "accounts_userprofile table not found. "
            "Run makemigrations and migrate."
        )

    def test_transactions_category_model_exists(self):
        """Test that Category model from transactions app has database table."""
        from transactions.models import Category

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_name = %s
            """, [Category._meta.db_table])
            result = cursor.fetchone()

        self.assertIsNotNone(
            result,
            "transactions_category table not found. "
            "Run makemigrations and migrate."
        )

    def test_transactions_transaction_model_exists(self):
        """Test that Transaction model from transactions app has database table."""
        from transactions.models import Transaction

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_name = %s
            """, [Transaction._meta.db_table])
            result = cursor.fetchone()

        self.assertIsNotNone(
            result,
            "transactions_transaction table not found. "
            "Run makemigrations and migrate."
        )

    def test_transaction_indexes_exist(self):
        """
        Test that database indexes are created for Transaction model.

        According to T011, Transaction should have indexes on:
        - [user, date]
        - [user, type]
        - [category]
        """
        from transactions.models import Transaction
        table_name = Transaction._meta.db_table

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT indexname
                FROM pg_indexes
                WHERE tablename = %s
            """, [table_name])
            indexes = [row[0] for row in cursor.fetchall()]

        # Check that we have indexes (exact names are auto-generated by Django)
        # Just verify there are multiple indexes beyond the primary key
        self.assertGreater(
            len(indexes),
            1,
            f"Expected multiple indexes on {table_name}, found {len(indexes)}. "
            "Verify migrations include index definitions."
        )

    def test_userprofile_has_correct_fields(self):
        """Test UserProfile table has all expected fields."""
        from accounts.models import UserProfile

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = %s
            """, [UserProfile._meta.db_table])
            columns = [row[0] for row in cursor.fetchall()]

        expected_fields = [
            'id', 'user_id', 'display_name', 'avatar',
            'monthly_budget', 'created_at', 'updated_at'
        ]

        for field in expected_fields:
            self.assertIn(
                field,
                columns,
                f"Field {field} not found in {UserProfile._meta.db_table}. "
                "Check migrations."
            )

    def test_category_has_correct_fields(self):
        """Test Category table has all expected fields."""
        from transactions.models import Category

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = %s
            """, [Category._meta.db_table])
            columns = [row[0] for row in cursor.fetchall()]

        expected_fields = [
            'id', 'name', 'icon', 'type', 'color', 'created_at'
        ]

        for field in expected_fields:
            self.assertIn(
                field,
                columns,
                f"Field {field} not found in {Category._meta.db_table}. "
                "Check migrations."
            )

    def test_transaction_has_correct_fields(self):
        """Test Transaction table has all expected fields."""
        from transactions.models import Transaction

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = %s
            """, [Transaction._meta.db_table])
            columns = [row[0] for row in cursor.fetchall()]

        expected_fields = [
            'id', 'user_id', 'category_id', 'type', 'amount',
            'date', 'note', 'created_at', 'updated_at'
        ]

        for field in expected_fields:
            self.assertIn(
                field,
                columns,
                f"Field {field} not found in {Transaction._meta.db_table}. "
                "Check migrations."
            )
