# Generated by Django 4.2.26 on 2025-11-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (emoji)')),
                ('transaction_type', models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu')], max_length=10, verbose_name='Loại giao dịch')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='Màu sắc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['transaction_type', 'name'],
            },
        ),
    ]
