# Generated by Django 4.2.26 on 2025-11-06 04:16

from django.db import migrations


def seed_categories(apps, schema_editor):
    """Seed default categories (Money Lover style)."""
    Category = apps.get_model('transactions', 'Category')
    
    # Danh mục Chi tiêu (Expense)
    expense_categories = [
        {'name': 'Ăn uống', 'icon': '🍔', 'color': '#FF5722'},
        {'name': 'Di chuyển & Xăng xe', 'icon': '🚗', 'color': '#2196F3'},
        {'name': 'Nhà cửa & Sinh hoạt', 'icon': '🏠', 'color': '#9C27B0'},
        {'name': 'Giải trí', 'icon': '🎬', 'color': '#E91E63'},
        {'name': 'Mua sắm', 'icon': '👕', 'color': '#FF9800'},
        {'name': 'Sức khỏe', 'icon': '💊', 'color': '#F44336'},
        {'name': 'Giáo dục', 'icon': '📚', 'color': '#3F51B5'},
        {'name': 'Gia đình & Con cái', 'icon': '👨\u200d👩\u200d👧', 'color': '#00BCD4'},
        {'name': 'Quà tặng & Quyên góp', 'icon': '💝', 'color': '#E91E63'},
        {'name': 'Công việc', 'icon': '💼', 'color': '#607D8B'},
        {'name': 'Điện thoại & Internet', 'icon': '📱', 'color': '#009688'},
        {'name': 'Du lịch', 'icon': '✈️', 'color': '#00BCD4'},
        {'name': 'Chi tiêu khác', 'icon': '💰', 'color': '#9E9E9E'},
    ]
    
    # Danh mục Thu nhập (Income)
    income_categories = [
        {'name': 'Lương', 'icon': '💵', 'color': '#4CAF50'},
        {'name': 'Thưởng', 'icon': '💼', 'color': '#8BC34A'},
        {'name': 'Quà tặng', 'icon': '🎁', 'color': '#CDDC39'},
        {'name': 'Đầu tư', 'icon': '📈', 'color': '#4CAF50'},
        {'name': 'Thu nhập khác', 'icon': '💰', 'color': '#689F38'},
    ]
    
    # Create expense categories
    for cat_data in expense_categories:
        Category.objects.get_or_create(
            name=cat_data['name'],
            transaction_type='expense',
            defaults={
                'icon': cat_data['icon'],
                'color': cat_data['color'],
            }
        )
    
    # Create income categories
    for cat_data in income_categories:
        Category.objects.get_or_create(
            name=cat_data['name'],
            transaction_type='income',
            defaults={
                'icon': cat_data['icon'],
                'color': cat_data['color'],
            }
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded categories."""
    Category = apps.get_model('transactions', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
